//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticalResults.TransportServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransportServiceReference.ITransportService")]
    public interface ITransportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportService/RequestNotification", ReplyAction="http://tempuri.org/ITransportService/RequestNotificationResponse")]
        bool RequestNotification(string notificationUid, string address, string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ITransportServiceChannel : CriticalResults.TransportServiceReference.ITransportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TransportServiceClient : System.ServiceModel.ClientBase<CriticalResults.TransportServiceReference.ITransportService>, CriticalResults.TransportServiceReference.ITransportService {
        
        public TransportServiceClient() {
        }
        
        public TransportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RequestNotification(string notificationUid, string address, string value) {
            return base.Channel.RequestNotification(notificationUid, address, value);
        }
    }
}
